language: node_js
sudo: false
node_js:
  - '4.2.4'
before_deploy:
  - npm install json
  - node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f packages/eslint-config-nikita/package.json -I
  - node_modules/.bin/json -E "this.version='$TRAVIS_TAG'" -f package.json -I
  - cd packages/eslint-config-nikita
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: JanS@DracoBlue.de
  api_key:
    secure: UqlkX1JFSs224a/dSHWdnIfUARg4onn2C5nk76KWqTJu9un4ewcVZez7uEYUPyYMU9VQigqaakm2SP5/dfAY1wbI2aUT7Ry/co0LHaLLwLmEjzZLo1jI6q9imZz/SPuswEJi1UTipdb9W5TLaGxIkcxidiCCrHlsHsyjx31Kxg4=
  on:
    tags: true
    repo: nikita-kit/nikita-js
    all_branches: true
    node: 4.2.4
